site_name: Voxail - AI-Powered Audio Transcription Platform
site_url: https://markkimotho.github.io/transcribe-ai/
repo_url: https://github.com/Markkimotho/transcribe-ai
repo_name: Markkimotho/transcribe-ai
docs_dir: docs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle: { icon: material/weather-night, name: Switch to dark mode }
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle: { icon: material/weather-sunny, name: Switch to light mode }
  features:
    - navigation.top
    - content.code.copy
    - toc.follow

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
